name: /hdd2/kai/Dynamic_Human_Robot_Value_Alignments/env
channels:
  - aihabitat-nightly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=24.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cmake=3.14.0
  - colorama=0.4.6
  - contourpy=1.0.2
  - cycler=0.12.1
  - dbus=1.13.18
  - expat=2.6.3
  - ffmpeg=4.3.2
  - fontconfig=2.14.1
  - fonttools=4.54.1
  - freetype=2.10.4
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - habitat-sim-mutex=1.0
  - icu=73.1
  - imageio=2.35.1
  - imageio-ffmpeg=0.5.1
  - importlib_resources=6.4.5
  - jbig=2.1
  - jpeg=9e
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=2.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.9.1
  - libdeflate=1.7
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.78.4
  - libgomp=14.1.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libpq=12.17
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=1.41.5
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxkbcommon=1.0.3
  - libxml2=2.13.1
  - lz4-c=1.9.4
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - munkres=1.1.4
  - mysql=5.7.20
  - ncurses=6.4
  - nettle=3.6
  - olefile=0.47
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.2
  - packaging=24.1
  - pcre2=10.42
  - pip=24.2
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - python=3.9.20
  - python-dateutil=2.9.0
  - python_abi=3.9
  - qt-main=5.15.2
  - quaternion=2022.4.3
  - readline=8.2
  - rhash=1.4.3
  - sip=6.5.1
  - six=1.16.0
  - smmap=3.0.5
  - sqlite=3.45.3
  - tk=8.6.14
  - toml=0.10.2
  - tornado=6.4.1
  - tqdm=4.66.5
  - typing_extensions=4.12.2
  - unicodedata2=15.1.0
  - wheel=0.44.0
  - withbullet=2.0
  - x264=1!161.3030
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxcursor=1.2.2
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.11
  - xorg-xorgproto=2024.1
  - xz=5.4.6
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==0.28.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - airportsdata==20241001
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - astor==0.8.1
      - async-timeout==4.0.3
      - av==12.2.0
      - blake3==1.0.4
      - blessed==1.20.0
      - braceexpand==0.1.7
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorful==0.5.6
      - compressed-tensors==0.8.0
      - cython==3.0.11
      - datasets==3.2.0
      - decorator==4.4.2
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.8
      - faster-fifo==1.4.7
      - filelock==3.16.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - fvcore==0.1.5.post20221221
      - gguf==0.9.1
      - git-filter-repo==2.38.0
      - google-api-core==2.24.1
      - google-auth==2.35.0
      - google-auth-oauthlib==0.4.6
      - googleapis-common-protos==1.66.0
      - gpustat==1.1.1
      - grpcio==1.66.2
      - gym==0.23.0
      - gym-notices==0.0.8
      - h11==0.14.0
      - habitat-sim==0.3.1
      - httpcore==1.0.5
      - httptools==0.6.4
      - httpx==0.27.0
      - huggingface-hub==0.28.1
      - hydra-core==1.3.2
      - idna==3.10
      - ifcfg==0.24
      - importlib-metadata==8.5.0
      - iniconfig==2.0.0
      - interegular==0.3.3
      - iopath==0.1.10
      - jinja2==3.1.4
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - lark==1.2.2
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.6
      - lmdb==1.5.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.1
      - mdurl==0.1.2
      - mistral-common==1.5.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multicoretsne==0.1
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - objectio==0.2.29
      - omegaconf==2.3.0
      - openai==1.61.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - opentsne==1.0.2
      - outlines==0.0.46
      - outlines-core==0.1.26
      - pandas==2.2.2
      - parameterized==0.9.0
      - partial-json-parser==0.2.1.1.post5
      - peft==0.10.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - portalocker==2.10.1
      - proglog==0.1.10
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.2
      - propcache==0.2.0
      - proto-plus==1.26.0
      - protobuf==5.29.3
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyairports==2.1.1
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pybullet==3.0.4
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - pytest==8.3.4
      - python-dotenv==1.0.1
      - pytorchvideo==0.1.5
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - ray==2.41.0
      - referencing==0.36.2
      - regex==2024.5.15
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.9.2
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.11.4
      - sentence-transformers==3.0.1
      - sentencepiece==0.2.0
      - setuptools==75.1.0
      - shellingham==1.5.4
      - simplejson==3.19.3
      - smart-open==7.1.0
      - sniffio==1.3.1
      - starlette==0.45.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - transformers==4.48.2
      - triton==3.1.0
      - typer==0.12.5
      - tzdata==2024.2
      - urllib3==2.2.3
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - virtualenv==20.29.1
      - watchfiles==1.0.4
      - wcwidth==0.2.13
      - webdataset==0.1.40
      - websockets==14.2
      - werkzeug==3.0.4
      - wrapt==1.17.2
      - xformers==0.0.28.post3
      - xgrammar==0.1.11
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.15.1
prefix: /hdd2/kai/Dynamic_Human_Robot_Value_Alignments/env
